### ISSUE TITLE
Performance significantly worsens when deleting folders with many items

### ISSUE THREAD

**Issue by pgrunewald** [plone/plone.app.linkintegrity#100]
I was observerving the behavior, that the time for calculating all the breaches significantly worsens when dealing with folders with many items.

After inspecting this issue further, I found that an expensive part (`get_breaches_for_item`) is called multiple times (i.e. the number of childrens the folder contains!). However we have to call this part exactly **once** instead! There is a PR accompanied with this issue, that solves it. I have run some profiling benchmarks and came up with some ridiculous speedups:

A folder with 72 items: 
88.635s -> 3.175s (Speedup: 27.92x)

A folder with 21 Items:
7.575s -> 0.94s (Speedup: 8.06x)

I can also provide the complete profiling results of the two runs (unoptimized vs optimized), if requested.

**Comment by jensens** [comment]
closed with #101
