### ISSUE TITLE
Archetypes dependency 

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.linkintegrity#18]
plone.app.linkintegrity depends on plone.app.referenceablebehavior (in setup.py) which depends on AT.

If linkintegrity should be part of Plone 5 core there must be done some work:

1) remove plone.app.linkintegrity from core
or 
2) refactor in order to make Archetypes a soft dependency (split into at and dx subpackages or such).

1 is easy but a frameworkteam decision, 
2 is a real solution but work to be done before Plone 5 release.

**Comment by pbauer** [comment]
There is now a PLIP (https://github.com/plone/Products.CMFPlone/issues/698). Most of the work is already done. I will continue working on that next week.

**Comment by pbauer** [comment]
Fixed with 3.0
